services:
  nix-service:
    image: nixos/nix:2.25.3             # Update the Nix version regularly...
    container_name:
      nix-container

    ports:
      - "8888:8888"

    volumes:
      # Host directory
      - type: bind
        source: ${NIX_DOCKER_PATH:?Host path not set} # Mount this host directory
                                    # It's definitely simpler to use
                                    # `./` instead, but on Macs that doesn't work
                                    # because podman's virtual machine (podman machine) re-maps paths... This absolute path is thus machine-dependent...
                                    # In such case, one should thus define the environment variable.
        target: /nix-docker 

      # Podman volume
      - nix-store:/nix                  # Cache the nix store in the system-wide podman's volume on the host podman.
    command: tail -f /dev/null  # Keep the container running by executing this dummy command.
    working_dir: /nix-docker    # Enter this working directory.

volumes:
  nix-store: # This volume is maintained by podman (or Docker) and is reused even after the container is destroyed.
    driver: local
